<?php
return array (
  'mxcms' => 
  array (
    's1' => 
    array (
      'logo1' => 'mxstatic/image/logo.png',
      'logo2' => 'mxstatic/picture/logo.png',
      'pic' => 'mxstatic/image/loading.gif',
      'pic1' => 'mxstatic/image/loading.gif',
      'gg' => 'mxone',
      'searchwd' => '搜索电影、电视剧、综艺、动漫',
      'sm' => '本站所有内容均来自互联网分享站点所提供的公开引用资源，未提供资源上传、存储服务。',
    ),
    's2' => 
    array (
      'qzslt' => '0',
      'pcgddh' => '1',
      'gddhbg' => '0',
      'gddhbgdm' => '',
      'zhiboym' => '0',
      'diyliveicon' => 'iconfont icon-zhibo',
      'sydh' => '1',
      'sydhicon' => 'icon-all',
      'sydhall' => '',
      'daohangid' => 'parent',
      'pcdhicon' => '1',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'num6' => '6',
      'icon6' => '',
      'num7' => '7',
      'icon7' => '',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
      'diy3' => '0',
      'diy3name' => '',
      'diy3url' => '',
      'diy3icon' => 'iconfont icon-zidingyiquyu',
      'wapsydh' => '1',
      'yxjcd' => '1',
      'yxjdiy' => '0',
      'cdbjys' => '',
      'iconbjys' => '',
      'iconztys' => '',
      'iconbjglys' => '',
      'yjqh' => '1',
      'liuyan' => '1',
      'topic' => '1',
      'dbdh' => '1',
      'todaygx' => '1',
      'todaycss' => '#FF0000',
      'listphb' => '1',
      'listphbname' => '月榜',
      'listphbtj' => '',
      'listphbby' => 'hits_month',
      'indextopic' => '1',
      'indextopicnum' => '4',
      'indexart' => '1',
      'indexartid' => '5',
      'indexartnum' => '6',
      'slide' => '1',
      'slidetj' => '5',
      'slidenum' => '8',
      'slidediy1' => '0',
      'slidediy1name' => '',
      'slidediy1pic' => '',
      'slidediy1url' => '',
      'slidediy2' => '0',
      'slidediy2name' => '',
      'slidediy2pic' => '',
      'slidediy2url' => '',
      'slidediy3' => '0',
      'slidediy3name' => '',
      'slidediy3pic' => '',
      'slidediy3url' => '',
      'slidediy4' => '0',
      'slidediy4name' => '',
      'slidediy4pic' => '',
      'slidediy4url' => '',
      'slidediy5' => '0',
      'slidediy5name' => '',
      'slidediy5pic' => '',
      'slidediy5url' => '',
      'hot' => '1',
      'hoticon' => '0',
      'hoticoncss' => '#FF0',
      'hotlevel' => '1',
      'hotall' => 'all',
      'logtype' => '1,2,3,4',
      'lbiconkg' => '0',
      'lbiconcss' => '#FF0000',
      'lbiconmr' => 'iconfont icon-kongbaiwendang',
      'lbnum1' => '1',
      'lbicon1' => 'icon-cate-dy',
      'lbnum2' => '2',
      'lbicon2' => 'icon-cate-ds',
      'lbnum3' => '3',
      'lbicon3' => 'icon-cate-zy',
      'lbnum4' => '4',
      'lbicon4' => 'icon-cate-dm',
      'lbnum5' => '5',
      'lbicon5' => 'iconfont icon-zixun2',
      'lbnum6' => '6',
      'lbicon6' => '',
      'lbnum7' => '7',
      'lbicon7' => '',
      'lbnum8' => '8',
      'lbicon8' => '',
      'listlevel' => '',
      'new' => '1',
      'newnewicon' => '0',
      'newiconcss' => '#FF0',
      'newids' => 'parent',
      'mryj' => '0',
      'searchhoticon' => '1',
      'tagkg' => '1',
      'tzzt' => '1',
      'xght' => '1',
      'about' => '1',
      'dbtop' => '1',
      'doubanlj' => '1',
      'user' => '1',
      'shoucang' => '1',
      'comment' => '1',
      'detailen' => '1',
      'miniplay' => '0',
      'tc' => '1',
      'tc_noti' => '<p>欢迎使用Mxone模板</p>
<p>本次更新内容</p>
<p>主题后台,分集剧情,明星页,相关话题,修复BUG</p>
<p>感谢你的支持</p>',
      'bftip' => '1',
      'bftips1' => '不要轻易相信视频中的任何广告，谨防上当受骗',
      'bftips2' => '如遇视频无法播放或加载速度慢，可尝试切换播放节点或者切换解析',
      'app' => '1',
      'app_url' => '',
      'app_url2' => '',
      'wz0' => '1',
      'web1' => 'www.xiangkanzy.com',
      'wz01' => '1',
      'web2' => 'www.xiangkanzy.com',
      'wz2' => '1',
      'web3' => 'www.xiangkanzy.com',
      'wz3' => '0',
      'web4' => 'www.xiangkanzy.com',
      'wz4' => '0',
      'web5' => 'www.xiangkanzy.com',
      'wz5' => '0',
    ),
    's5' => 
    array (
      'wapdaohangid' => 'parent',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'num6' => '6',
      'icon6' => '',
      'num7' => '7',
      'icon7' => '',
      'num8' => '8',
      'icon8' => '',
      'num9' => '9',
      'icon9' => '',
      'num10' => '10',
      'icon10' => '',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
    ),
    's6' => 
    array (
      'wapdaohangid' => 'parent',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
    ),
    's7' => 
    array (
      'hotpxb' => '1',
      'hotlevel' => '',
      'hotnum' => '10',
      'zztjb' => '1',
      'zztjlevel' => 'all',
      'zztjnum' => '10',
      'diytopidslevel' => '',
      'diytopidsnum' => '10',
      'diytopids' => '1,2,3,4',
      'iconmr' => 'iconfont icon-zhibo',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => '',
      'num6' => '6',
      'icon6' => '',
    ),
    's3' => 
    array (
      'adqj' => '0',
      'aadqj' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位05</h3></div>',
      'ad1' => '0',
      'aad1' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位01</h3></div>',
      'addb' => '0',
      'aaddb' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位06</h3></div>',
      'ad2' => '0',
      'aad2' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位02</h3></div>',
      'ad3' => '0',
      'aad3' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-top: 20px;"> <h3 style="text-align: center;">广告位03</h3></div>',
      'ad4' => '0',
      'aad4' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位04</h3></div>',
      'pcad1' => '0',
      'pcaad1' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位01</h3></div>',
      'pcad2' => '0',
      'pcaad2' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位02</h3></div>',
      'pcad3' => '0',
      'pcaad3' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-top: 20px;"> <h3 style="text-align: center;">广告位03</h3></div>',
      'pcad4' => '0',
      'pcaad4' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位04</h3></div>',
      'wapad1' => '0',
      'wapaad1' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位01</h3></div>',
      'wapad2' => '0',
      'wapaad2' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位02</h3></div>',
      'wapad3' => '0',
      'wapaad3' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-top: 20px;"> <h3 style="text-align: center;">广告位03</h3></div>',
      'wapad4' => '0',
      'wapaad4' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位04</h3></div>',
    ),
    's4' => 
    array (
      'shier' => '0',
      'ctrl' => '0',
      'right' => '0',
      'mode' => '0',
      'pbtips' => '你知道的太多了',
      'tbdm' => '1',
      'tbdmtips' => '<meta name="referrer" content="always"> 
<meta name="referrer" content="no-referrer" />',
      'dbdm' => '1',
      'dbdmtips' => '统计代码',
      'stylediy' => '0',
      'stylecss' => '',
    ),
  ),
);