<?php
return array (
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '线路❶',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9999',
    'tip' => '无需安装任何插件（腾讯视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'qq',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '线路❷',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9998',
    'tip' => '无需安装任何插件（爱奇艺视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'qiyi',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '线路❸',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9997',
    'tip' => '无需安装任何插件（优酷视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'youku',
  ),
  'migu' => 
  array (
    'status' => '1',
    'from' => 'migu',
    'show' => '线路❹',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9996',
    'tip' => '无需安装任何插件（咪咕视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'migu',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '线路❺',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9995',
    'tip' => '无需安装任何插件（芒果视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'mgtv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => '线路❻',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9994',
    'tip' => '无需安装任何插件（pptv视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'pptv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '线路❼',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9993',
    'tip' => '无需安装任何插件（letv视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'letv',
  ),
  'bilibili' => 
  array (
    'status' => '1',
    'from' => 'bilibili',
    'show' => '线路❿',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9992',
    'tip' => '无需安装任何插件（哔哩视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'bilibili',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '线路❽',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9992',
    'tip' => '无需安装任何插件（sohu视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'sohu',
  ),
  'm1905' => 
  array (
    'status' => '1',
    'from' => 'm1905',
    'show' => '线路❾',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=',
    'parse2' => '',
    'sort' => '9991',
    'tip' => '无需安装任何插件（m1905视频）',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'm1905',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => '红牛在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'http://okjx.cc/?url=,https://jx.xmflv.com/?url=',
    'parse2' => 'https://jsap.attakids.com/?url=,https://fast.rongxingvr.cn:8866/api/?type=app&key=TIC7NUrsYUQAu27Yyn&url=',
    'sort' => '1193',
    'tip' => '无需安装任何插件',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'hnm3u8',
  ),
);